#!/usr/bin/env python
"""
=============================================================================
MultiQC Custom Content: DESeq2 QC Reference Module
=============================================================================

This module provides custom content configuration for DESeq2 QC plots
generated by the ChIP-seq pipeline to be integrated into MultiQC reports.

Supported plot types:
- PCA plots (all genes and top variable genes)
- Sample distance heatmaps
- Sample correlation heatmaps (Pearson)

File patterns recognized:
- *.pca.vals.txt - PCA coordinates (all genes)
- *.pca.top*.vals.txt - PCA coordinates (top N variable genes)
- *.sample.dists.txt - Sample-to-sample distances
- *.sample.correlations.txt - Pearson correlation matrix

The module configuration automatically:
1. Detects normalization method (all_genes vs invariant_genes)
2. Groups plots by normalization method
3. Creates sections under parent "DESeq2 FeatureCounts QC"
4. Applies consistent ordering and styling

Author: Seqera AI
Version: 1.0.0
License: MIT
=============================================================================
"""


# MultiQC Custom Content Configuration for DESeq2 QC
# This dictionary defines how MultiQC should parse and display DESeq2 QC files

custom_content_config = {
    # Parent section configuration
    'parent_name': 'DESeq2 FeatureCounts QC',
    'parent_id': 'deseq2_featurecounts_qc',
    'parent_description': 'Quality control plots from DESeq2 normalization and analysis of FeatureCounts data',
    
    # Plot configurations organized by type
    'plots': {
        
        # PCA - All Genes (All Genes normalization)
        'pca_all_genes_all': {
            'id': 'deseq2_pca_all_genes_all',
            'section_name': '01. PCA - All Genes (All Genes Normalization)',
            'description': 'Principal Component Analysis using all genes with all-genes normalization method',
            'plot_type': 'scatter',
            'pconfig': {
                'id': 'deseq2_pca_all_genes_all_plot',
                'title': 'DESeq2: PCA - All Genes (All Genes)',
                'xlab': 'PC1',
                'ylab': 'PC2',
                'marker_size': 8,
            },
            'sp': {
                'fn': '*all_genes.pca.vals.txt',
                'contents': 'PC1',
            }
        },
        
        # PCA - Top Genes (All Genes normalization)
        'pca_top_all_genes': {
            'id': 'deseq2_pca_top_all_genes',
            'section_name': '02. PCA - Top 500 Variable Genes (All Genes Normalization)',
            'description': 'Principal Component Analysis using top 500 most variable genes with all-genes normalization',
            'plot_type': 'scatter',
            'pconfig': {
                'id': 'deseq2_pca_top_all_genes_plot',
                'title': 'DESeq2: PCA - Top Variable Genes (All Genes)',
                'xlab': 'PC1',
                'ylab': 'PC2',
                'marker_size': 8,
            },
            'sp': {
                'fn': '*all_genes.pca.top*.vals.txt',
                'contents': 'PC1',
            }
        },
        
        # Sample Distances (All Genes normalization)
        'distances_all_genes': {
            'id': 'deseq2_distances_all_genes',
            'section_name': '03. Sample Distances (All Genes Normalization)',
            'description': 'Euclidean distances between samples based on variance-stabilized transformation with all-genes normalization',
            'plot_type': 'heatmap',
            'pconfig': {
                'id': 'deseq2_distances_all_genes_heatmap',
                'title': 'DESeq2: Sample Distances (All Genes)',
                'square': True,
                'colstops': [
                    [0, '#08306B'],
                    [0.125, '#08519C'],
                    [0.25, '#2171B5'],
                    [0.375, '#4292C6'],
                    [0.5, '#6BAED6'],
                    [0.625, '#9ECAE1'],
                    [0.75, '#C6DBEF'],
                    [0.875, '#DEEBF7'],
                    [1.0, '#F7FBFF']
                ],
            },
            'sp': {
                'fn': '*all_genes.sample.dists.txt',
            }
        },
        
        # Sample Correlations (All Genes normalization) - Optional
        'correlations_all_genes': {
            'id': 'deseq2_correlations_all_genes',
            'section_name': '04. Sample Correlations (All Genes Normalization)',
            'description': 'Pearson correlation matrix between samples with all-genes normalization',
            'plot_type': 'heatmap',
            'pconfig': {
                'id': 'deseq2_correlations_all_genes_heatmap',
                'title': 'DESeq2: Sample Correlations (All Genes)',
                'square': True,
                'min': -1.0,
                'max': 1.0,
                'colstops': [
                    [0, '#D73027'],
                    [0.25, '#FC8D59'],
                    [0.5, '#FFFFBF'],
                    [0.75, '#91BFDB'],
                    [1.0, '#4575B4']
                ],
            },
            'sp': {
                'fn': '*all_genes.sample.correlations.txt',
            }
        },
        
        # PCA - All Genes (Invariant Genes normalization)
        'pca_all_genes_invariant': {
            'id': 'deseq2_pca_all_genes_invariant',
            'section_name': '05. PCA - All Genes (Invariant Genes Normalization)',
            'description': 'Principal Component Analysis using all genes with invariant-genes normalization method',
            'plot_type': 'scatter',
            'pconfig': {
                'id': 'deseq2_pca_all_genes_invariant_plot',
                'title': 'DESeq2: PCA - All Genes (Invariant Genes)',
                'xlab': 'PC1',
                'ylab': 'PC2',
                'marker_size': 8,
            },
            'sp': {
                'fn': '*invariant_genes.pca.vals.txt',
                'contents': 'PC1',
            }
        },
        
        # PCA - Top Genes (Invariant Genes normalization)
        'pca_top_invariant': {
            'id': 'deseq2_pca_top_invariant',
            'section_name': '06. PCA - Top 500 Variable Genes (Invariant Genes Normalization)',
            'description': 'Principal Component Analysis using top 500 most variable genes with invariant-genes normalization',
            'plot_type': 'scatter',
            'pconfig': {
                'id': 'deseq2_pca_top_invariant_plot',
                'title': 'DESeq2: PCA - Top Variable Genes (Invariant Genes)',
                'xlab': 'PC1',
                'ylab': 'PC2',
                'marker_size': 8,
            },
            'sp': {
                'fn': '*invariant_genes.pca.top*.vals.txt',
                'contents': 'PC1',
            }
        },
        
        # Sample Distances (Invariant Genes normalization)
        'distances_invariant': {
            'id': 'deseq2_distances_invariant',
            'section_name': '07. Sample Distances (Invariant Genes Normalization)',
            'description': 'Euclidean distances between samples based on variance-stabilized transformation with invariant-genes normalization',
            'plot_type': 'heatmap',
            'pconfig': {
                'id': 'deseq2_distances_invariant_heatmap',
                'title': 'DESeq2: Sample Distances (Invariant Genes)',
                'square': True,
                'colstops': [
                    [0, '#08306B'],
                    [0.125, '#08519C'],
                    [0.25, '#2171B5'],
                    [0.375, '#4292C6'],
                    [0.5, '#6BAED6'],
                    [0.625, '#9ECAE1'],
                    [0.75, '#C6DBEF'],
                    [0.875, '#DEEBF7'],
                    [1.0, '#F7FBFF']
                ],
            },
            'sp': {
                'fn': '*invariant_genes.sample.dists.txt',
            }
        },
        
        # Sample Correlations (Invariant Genes normalization) - Optional
        'correlations_invariant': {
            'id': 'deseq2_correlations_invariant',
            'section_name': '08. Sample Correlations (Invariant Genes Normalization)',
            'description': 'Pearson correlation matrix between samples with invariant-genes normalization',
            'plot_type': 'heatmap',
            'pconfig': {
                'id': 'deseq2_correlations_invariant_heatmap',
                'title': 'DESeq2: Sample Correlations (Invariant Genes)',
                'square': True,
                'min': -1.0,
                'max': 1.0,
                'colstops': [
                    [0, '#D73027'],
                    [0.25, '#FC8D59'],
                    [0.5, '#FFFFBF'],
                    [0.75, '#91BFDB'],
                    [1.0, '#4575B4']
                ],
            },
            'sp': {
                'fn': '*invariant_genes.sample.correlations.txt',
            }
        },
    }
}


# YAML Configuration Template for MultiQC Config File
# This can be copied to multiqc_config.yaml for easier configuration

multiqc_config_yaml = """
# DESeq2 QC Custom Content Configuration
# Add this to your multiqc_config.yaml file

custom_data:
  deseq2_qc:
    parent_name: 'DESeq2 FeatureCounts QC'
    parent_id: 'deseq2_featurecounts_qc'
    parent_description: 'Quality control plots from DESeq2 normalization and analysis'
    
    # PCA - All Genes (All Genes Normalization)
    pca_all_genes_all:
      id: 'deseq2_pca_all_genes_all'
      section_name: '01. PCA - All Genes (All Genes Normalization)'
      description: 'Principal Component Analysis using all genes with all-genes normalization'
      plot_type: 'scatter'
      pconfig:
        id: 'deseq2_pca_all_genes_all_plot'
        title: 'DESeq2: PCA - All Genes (All Genes)'
        xlab: 'PC1'
        ylab: 'PC2'
      sp:
        fn: '*all_genes.pca.vals.txt'
        contents: 'PC1'
    
    # PCA - Top 500 Variable Genes (All Genes Normalization)
    pca_top_all_genes:
      id: 'deseq2_pca_top_all_genes'
      section_name: '02. PCA - Top 500 Variable Genes (All Genes Normalization)'
      description: 'Principal Component Analysis using top 500 most variable genes'
      plot_type: 'scatter'
      pconfig:
        id: 'deseq2_pca_top_all_genes_plot'
        title: 'DESeq2: PCA - Top Variable Genes (All Genes)'
        xlab: 'PC1'
        ylab: 'PC2'
      sp:
        fn: '*all_genes.pca.top*.vals.txt'
        contents: 'PC1'
    
    # Sample Distances (All Genes Normalization)
    distances_all_genes:
      id: 'deseq2_distances_all_genes'
      section_name: '03. Sample Distances (All Genes Normalization)'
      description: 'Euclidean distances between samples (all-genes normalization)'
      plot_type: 'heatmap'
      pconfig:
        id: 'deseq2_distances_all_genes_heatmap'
        title: 'DESeq2: Sample Distances (All Genes)'
        square: true
      sp:
        fn: '*all_genes.sample.dists.txt'
    
    # Sample Correlations (All Genes Normalization)
    correlations_all_genes:
      id: 'deseq2_correlations_all_genes'
      section_name: '04. Sample Correlations (All Genes Normalization)'
      description: 'Pearson correlation matrix (all-genes normalization)'
      plot_type: 'heatmap'
      pconfig:
        id: 'deseq2_correlations_all_genes_heatmap'
        title: 'DESeq2: Sample Correlations (All Genes)'
        square: true
        min: -1.0
        max: 1.0
      sp:
        fn: '*all_genes.sample.correlations.txt'
    
    # PCA - All Genes (Invariant Genes Normalization)
    pca_all_genes_invariant:
      id: 'deseq2_pca_all_genes_invariant'
      section_name: '05. PCA - All Genes (Invariant Genes Normalization)'
      description: 'Principal Component Analysis using all genes with invariant-genes normalization'
      plot_type: 'scatter'
      pconfig:
        id: 'deseq2_pca_all_genes_invariant_plot'
        title: 'DESeq2: PCA - All Genes (Invariant Genes)'
        xlab: 'PC1'
        ylab: 'PC2'
      sp:
        fn: '*invariant_genes.pca.vals.txt'
        contents: 'PC1'
    
    # PCA - Top 500 Variable Genes (Invariant Genes Normalization)
    pca_top_invariant:
      id: 'deseq2_pca_top_invariant'
      section_name: '06. PCA - Top 500 Variable Genes (Invariant Genes Normalization)'
      description: 'Principal Component Analysis using top 500 most variable genes'
      plot_type: 'scatter'
      pconfig:
        id: 'deseq2_pca_top_invariant_plot'
        title: 'DESeq2: PCA - Top Variable Genes (Invariant Genes)'
        xlab: 'PC1'
        ylab: 'PC2'
      sp:
        fn: '*invariant_genes.pca.top*.vals.txt'
        contents: 'PC1'
    
    # Sample Distances (Invariant Genes Normalization)
    distances_invariant:
      id: 'deseq2_distances_invariant'
      section_name: '07. Sample Distances (Invariant Genes Normalization)'
      description: 'Euclidean distances between samples (invariant-genes normalization)'
      plot_type: 'heatmap'
      pconfig:
        id: 'deseq2_distances_invariant_heatmap'
        title: 'DESeq2: Sample Distances (Invariant Genes)'
        square: true
      sp:
        fn: '*invariant_genes.sample.dists.txt'
    
    # Sample Correlations (Invariant Genes Normalization)
    correlations_invariant:
      id: 'deseq2_correlations_invariant'
      section_name: '08. Sample Correlations (Invariant Genes Normalization)'
      description: 'Pearson correlation matrix (invariant-genes normalization)'
      plot_type: 'heatmap'
      pconfig:
        id: 'deseq2_correlations_invariant_heatmap'
        title: 'DESeq2: Sample Correlations (Invariant Genes)'
        square: true
        min: -1.0
        max: 1.0
      sp:
        fn: '*invariant_genes.sample.correlations.txt'

sp:
  deseq2_qc:
    fn: '*.{pca.vals,pca.top*vals,sample.dists,sample.correlations}.txt'
"""


# Usage Instructions
USAGE = """
=============================================================================
USAGE INSTRUCTIONS: DESeq2 QC Reference Module
=============================================================================

This module provides configuration for integrating DESeq2 QC plots into
MultiQC reports. There are two ways to use it:

METHOD 1: Copy Configuration to multiqc_config.yaml (RECOMMENDED)
------------------------------------------------------------------
1. Copy the YAML configuration from the 'multiqc_config_yaml' variable above
2. Paste it into your pipeline's multiqc_config.yaml file
3. MultiQC will automatically detect and parse DESeq2 QC files

METHOD 2: Use Python Dictionary in Custom MultiQC Module
---------------------------------------------------------
1. Import this module in your custom MultiQC plugin:
   from deseq2_qc_reference import custom_content_config
   
2. Use the configuration dictionary to set up custom content parsing

FILE NAMING CONVENTIONS:
------------------------
Your DESeq2 QC output files should follow these patterns:

All Genes Normalization:
  - <sample>_all_genes.pca.vals.txt
  - <sample>_all_genes.pca.top500.vals.txt (or any number after 'top')
  - <sample>_all_genes.sample.dists.txt
  - <sample>_all_genes.sample.correlations.txt

Invariant Genes Normalization:
  - <sample>_invariant_genes.pca.vals.txt
  - <sample>_invariant_genes.pca.top500.vals.txt
  - <sample>_invariant_genes.sample.dists.txt
  - <sample>_invariant_genes.sample.correlations.txt

EXPECTED FILE FORMAT:
---------------------
PCA files (*.pca.vals.txt, *.pca.top*.vals.txt):
  sample\tPC1\tPC2\tPC3\t...
  sample1\t0.123\t-0.456\t0.789\t...
  sample2\t-0.234\t0.567\t-0.890\t...

Distance/Correlation files (*.sample.dists.txt, *.sample.correlations.txt):
  sample\tsample1\tsample2\tsample3\t...
  sample1\t0.0\t1.234\t2.345\t...
  sample2\t1.234\t0.0\t1.456\t...
  sample3\t2.345\t1.456\t0.0\t...

PLOT ORDERING:
--------------
Plots are automatically numbered and ordered:
01. PCA - All Genes (All Genes Normalization)
02. PCA - Top Variable Genes (All Genes Normalization)
03. Sample Distances (All Genes Normalization)
04. Sample Correlations (All Genes Normalization)
05. PCA - All Genes (Invariant Genes Normalization)
06. PCA - Top Variable Genes (Invariant Genes Normalization)
07. Sample Distances (Invariant Genes Normalization)
08. Sample Correlations (Invariant Genes Normalization)

TROUBLESHOOTING:
----------------
- Ensure file names match the patterns exactly
- Check that files are in the MultiQC search path
- Verify file format matches the expected structure
- Check MultiQC logs for parsing errors

For more information, see MultiQC documentation:
https://multiqc.info/docs/#custom-content
=============================================================================
"""


if __name__ == '__main__':
    print(USAGE)
    print("\n\nYAML Configuration Template:\n")
    print(multiqc_config_yaml)
